# Generated by Django 6.0.6 on 2026-07-09 04:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddConstraint(
            model_name='transaccion',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='monto_positivo'),
        ),
    ]
