# Generated by Django 6.0.6 on 2026-07-09 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_brand_image_productgroup_image_supplier_image'),
        ('purchasing', '0001_initial'),
        ('transaccion', '0002_alter_transaccion_monto_transaccion_monto_positivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='purchasing.purchase'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
