# Generated by Django 6.0.6 on 2026-07-09 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_brand_image_productgroup_image_supplier_image'),
        ('transaccion', '0003_transaccion_compra_transaccion_factura_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaccionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaccion_details', to='billing.product')),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='transaccion.transaccion')),
            ],
        ),
    ]
