# Generated by Django 6.0.6 on 2026-07-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('cargo', models.CharField(choices=[('vendedor', 'vendedor'), ('bodega', 'bodega'), ('admin', 'admin')], default='vendedor', max_length=10)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_ingreso', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
