# Generated by Django 6.0.6 on 2026-07-09 20:32

import shared.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_alter_empleado_fecha_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='cedula',
            field=models.CharField(max_length=10, unique=True, validators=[shared.validators.validate_cedula_ec]),
        ),
    ]
